// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDXvP9MV0w_OGZCJ0_5jEvy1E12BKtL2k',
    appId: '1:1006181741380:android:dad5665cdc89de899c5d11',
    messagingSenderId: '1006181741380',
    projectId: 'watch-shop-3cde6',
    storageBucket: 'watch-shop-3cde6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvSluhCfx3AjEV3GqBn6-UpYhi-noLbfU',
    appId: '1:1006181741380:ios:d6597f7d0e0f54189c5d11',
    messagingSenderId: '1006181741380',
    projectId: 'watch-shop-3cde6',
    storageBucket: 'watch-shop-3cde6.appspot.com',
    androidClientId: '1006181741380-hl70of1bnv0ud9mfavmg1vngds1ptlbv.apps.googleusercontent.com',
    iosClientId: '1006181741380-4lld6gi9v7f49pdkb9s858ak5d0qjtp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchShop',
  );
}
